trigger:
- main

pool:
  vmImage: 'vs2017-win2016'

variables:
  - group: ADO-TF-AWS-VPC-Int
  - name: region
    value: 'us-east-1'


# Install Terraform extension to use this task https://marketplace.visualstudio.com/items?itemName=ms-devlabs.custom-terraform-tasks&ssr=false#overview
steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: 'Install Terraform 0.14.0'
  inputs:
    terraformVersion: 0.14.0
# Terraform versions: https://releases.hashicorp.com/terraform/

- powershell: |
   Write-Host "This is the current working directory: $(build.sourcesdirectory)"
   terraform init -backend-config="bucket=skundu-terraform-remote-state" -backend-config="key=tf/ADO-TF-VPC-Int/terraform.tfstate" -backend-config="region=$(region)" -backend-config="access_key=$(access_key)" -backend-config="secret_key=$(secret_key)" -no-color
  workingDirectory: $(build.sourcesdirectory)
  displayName: 'terraform init'

- powershell: |
   terraform validate -json -no-color
  workingDirectory: $(build.sourcesdirectory)
  displayName: 'terraform validate'

- powershell: |
   terraform plan -var region=$(region) -var access_key=$(access_key) -var secret_key=$(secret_key) -out application.tfplan -no-color
  workingDirectory: $(build.sourcesdirectory)
  displayName: 'terraform plan'

- powershell: |
   terraform apply "application.tfplan" -no-color
  workingDirectory: $(build.sourcesdirectory)
  displayName: 'terraform apply'